
import { Geist, Geist_Mono, Jost } from "next/font/google";
import { Roboto, Open_Sans, Lato, Poppins } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./ReduxProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import MainLayout from './MainLayOut';
import { AuthProvider } from "./context/auth-context";
import { ResumeProvider } from "./context/ResumeContext";
// Font   
export const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  variable: "--font-roboto",
  display: "swap",
});

export const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
  variable: "--font-open-sans",
  display: "swap",
});

export const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--font-lato",
  display: "swap",
});

export const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const jost = Jost({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-jost",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Spreadnext — Where Careers Meet Community",
  description: "Generated by create next app",
  icons: {
    icon: "/spreads.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${jost.variable} ${roboto.variable} ${openSans.variable} ${lato.variable} ${poppins.variable} antialiased`}
      >
          <ReduxProvider>
        <AuthProvider>
    <ResumeProvider>
       <MainLayout>
          {children}
        </MainLayout>
         <ToastContainer
  position="top-left"
  autoClose={2000}          // <-- 2000ms = 2 seconds
  hideProgressBar={true} 
  newestOnTop={true}
  closeOnClick
  pauseOnFocusLoss={false}  // Window tab change karne par bhi timer na ruke
  pauseOnHover={false}      // Mouse upar le jaane par bhi hide ho jaye
  draggable
  theme="colored"
  toastClassName="custom-toast"
  bodyClassName="custom-toast-body"
/>
    </ResumeProvider>
        </AuthProvider>
           </ReduxProvider>
        
      </body>
    </html>
  );
}